STEAM_WISHLIST_URL = 'http://steamcommunity.com/profiles/{0}/wishlist'

CHEAP_SHARK_API_GET_GAMES_DEALS_BASE_URL = 'http://www.cheapshark.com/api/1.0/deals?{0}={{0}}'
CHEAP_SHARK_API_GET_GAME_DEALS_URL = CHEAP_SHARK_API_GET_GAMES_DEALS_BASE_URL.format('steamAppID')
CHEAP_SHARK_API_GET_DEAL_DETAILS_URL = CHEAP_SHARK_API_GET_GAMES_DEALS_BASE_URL.format('id')

STEAM_PAGE_HTML_ID = 'id'
STEAM_PAGE_HTML_ITEM_NAME = 'ellipsis'
STEAM_PAGE_HTML_ITEM_IMG = 'img'
STEAM_PAGE_HTML_ITEM_IMG_SRC = 'src'
STEAM_PAGE_HTML_ID_PREFIX_COUNT = 5
STEAM_PAGE_HTML_ITEM_CLASS = 'wishlistRow'
BEAUTIFUL_SOUP_HTML_PARSER = 'html.parser'

IGDB_FILTERS = 'filters'
IGDB_HLTB_TERM = 'time_to_beat'
IGDB_EXTERNAL_FILTER_PARAM = '[external.steam][eq]'
IGDB_FIELDS_PARAM = 'fields'
HLTB_TIME_CONVERT_STRING = '%dh:%02dm:%02ds'
