STEAM_WISHLIST_URL = 'http://steamcommunity.com/profiles/{0}/wishlist'

CHEAP_SHARK_API_BASE_URL = 'http://www.cheapshark.com/api/1.0{0}'

CHEAP_SHARK_API_BASE_GAME_URL = CHEAP_SHARK_API_BASE_URL.format('/games{0}')
CHEAP_SHARK_API_BASE_DEAL_URL = CHEAP_SHARK_API_BASE_URL.format('/deals{0}')

CHEAP_SHARK_API_GET_GAME_DETAILS_URL = CHEAP_SHARK_API_BASE_GAME_URL.format('?steamAppID={0}')
CHEAP_SHARK_API_GET_GAMES_DEALS_URL = CHEAP_SHARK_API_BASE_GAME_URL.format('?ids={0}')

STEAM_PAGE_HTML_ID = 'id'
STEAM_PAGE_HTML_ITEM_NAME = 'ellipsis'
STEAM_PAGE_HTML_ITEM_IMG = 'img'
STEAM_PAGE_HTML_ITEM_IMG_SRC = 'src'
STEAM_PAGE_HTML_ID_PREFIX_COUNT = 5
STEAM_PAGE_HTML_ITEM_CLASS = 'wishlistRow'
BEAUTIFUL_SOUP_HTML_PARSER = 'html.parser'

IGDB_NAME = 'name'
IGDB_HLTB_STATS = 'time_to_beat'
IGDB_SEARCH_PARAM = 'search'
IGDB_FIELDS_PARAM = 'fields'

